export const SET_TASK_LIST = 'SET_TASK_LIST';
export const SET_TASK = 'SET_TASK';
export const SET_IS_ADDRESS_MODAL_OPEN = 'SET_IS_ADDRESS_MODAL_OPEN';
export const SET_SCROLL_REF = 'SET_SCROLL_REF';
export const SET_COMMENTS_Y_POSITION = 'SET_COMMENTS_Y_POSITION';
